---
# tasks file for ansible-role-openvswitch
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
- name: Define openvswitch_packages.
  set_fact:
    apache_packages: "{{ openvswitch_packages | list }}"
  when: openvswitch_packages is not defined
- include_tasks: "{{ ansible_os_family }}-install.yml"
