---
driver:
  name: docker
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[auditd::default]
    verifier:
      inspec_tests:
        - name: dev-sec/linux-baseline
    #   limit testing to just the "package-08" control
      controls:
       - package-08
      format: json
      output: ./linux-baseline-results.json
    attributes:
