---
language: ruby
cache: bundler
bundler_args: --without integration
rvm:
  #- 2.3
  - 2.5
sudo: false
env:
  # global:
  #  - distribution=ubuntu
  #    version=18.04
  #  - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - INSTANCE=default-ubuntu-1604
  # - INSTANCE=default-ubuntu-1804
  # - INSTANCE=default-centos-74
services:
  - docker
before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 3.5.13
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
jobs:
  include:
    - stage: kitchen create
      script:
      - bundle exec rake
