---
language: ruby
cache: bundler
bundler_args: --without integration
rvm:
  #- 2.3
  - 2.5
sudo: required
env:
  global:
     - DOCKER_COMPOSE_VERSION=1.23.2
  #  - distribution=ubuntu
  #    version=18.04
  #  - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - INSTANCE=default-ubuntu-1604
  # - INSTANCE=default-ubuntu-1804
  # - INSTANCE=default-centos-74
services:
  - docker
before_install:
  # download the latest version of Docker Compose
  # ensure you have the latest version, check the Compose repository release page on GitHub.
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  # Apply executable permissions to the binary
  - sudo chmod +x /usr/local/bin/docker-compose
  # Test the installation
  - sudo docker-compose --version
  #  retrieve the latest workstation images
  - wget -q https://raw.githubusercontent.com/learn-chef/inspec/master/docker-compose.yml
  - sudo docker-compose pull
  # start the containers. The -d argument starts the containers in the background.
  - sudo docker-compose up -d
jobs:
  include:
    - stage: run dev-sec/linux-baseline profile from supermarket on container target.
      script:
      - sudo docker exec -d workstation inspec supermarket exec dev-sec/linux-baseline -t ssh://root:password@target
    - stage: run dev-sec/linux-baseline profile from github sources on container target. with "package-08" control
      script:
      - sudo docker exec -d workstation inspec exec https://github.com/dev-sec/linux-baseline -t ssh://root:password@target --controls package-08
    - stage: tear down the cluster
      script:
      - sudo docker-compose down --rmi all
    # - stage: rake run
    #   script:
    #   - bundle exec rake
